name: Common Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['26.0', '25.2.3', '24.1.2']
        rebar3_version: ['3.20.0']
        os: [ubuntu-20.04]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}

    - name: Compile
      run: rebar3 compile
    - name: Tests
      run: rebar3 ct --cover
    - name: Covertool
      run: rebar3 covertool generate
    - uses: codecov/codecov-action@v2
      if: ${{ always() }}
      with:
        file: _build/test/covertool/grpcbox.covertool.xml
        env_vars: OTP_VERSION

    - name: Setup Go 1.21.4
      uses: actions/setup-go@v4
      with:
        # Semantic version range syntax or exact version of Go
        go-version: '1.21.4'

    - uses: actions/checkout@v4
      with:
        repository: 'grpc/grpc-go'
        path: 'grpc-go'

    - name: Install grpc-go interop client
      run: |
        cd grpc-go
        go build -o ./go-grpc-interop-client ./interop/client

    - name: Run interop tests
      run: |
        rebar3 as interop release
        _build/interop/rel/grpc_interop/bin/grpc_interop daemon

        PATH=grpc-go/:$PATH interop/run_server_tests.sh

  dialyzer:
    name: Dialyze on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['26.0']
        rebar3_version: ['3.22.1']
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
        version-type: 'strict'
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles('rebar.lock') }}-5
        restore-keys: |
          ${{ runner.os }}-dialyzer-${{ matrix.otp_version }}-5-
    - name: Compile
      run: rebar3 compile
    - name: Dialyzer
      run: rebar3 as dialyzer dialyzer
